#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

# write the command to start your program here
CMD=""

log_msg() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>${LOG_FILE}
}

check_with_build() {
  if [ ! -f "${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" ]; then
    echo "Module file not found: ${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" >>${LOG_FILE}
    . "$(dirname "$0")/install_callback" >>${LOG_FILE}
    return $?
  fi

  vermagic_module=$(modinfo -F vermagic "${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" 2>/dev/null | awk '{printf $1}')
  vermagic_kernel=$(uname -r)
  if [ "${vermagic_module}" != "${vermagic_kernel}" ]; then
    echo "Module vermagic (${vermagic_module}) does not match kernel version (${vermagic_kernel})" >>${LOG_FILE}
    . "$(dirname "$0")/install_callback" >>${LOG_FILE}
    return $?
  fi

  return 0
}

insmod_from_file() {
  [ -z "${1}" ] && return 1
  local module_file module_name dep_modules
  module_file="$1"
  module_name=$(modinfo -F name "${module_file}" 2>/dev/null)
  dep_modules=$(modinfo -F depends "${module_file}" 2>/dev/null | tr ',' ' ')
  if [ -n "${dep_modules}" ]; then
    for dep in ${dep_modules}; do
      if ! lsmod | grep -q "^${dep}\b"; then
        modprobe "${dep}"
      fi
    done
  fi
  lsmod | grep -q "^${module_name}\b" && rmmod "${module_name}"
  insmod "${module_file}"
}

rmmod_from_file() {
  [ -z "${1}" ] && return 1
  local module_file module_name dep_modules
  module_file="$1"
  module_name=$(modinfo -F name "${module_file}" 2>/dev/null)
  # shellcheck disable=SC2034
  dep_modules=$(modinfo -F depends "${module_file}" 2>/dev/null | tr ',' ' ')
  # if [ -n "${dep_modules}" ]; then
  #   for dep in ${dep_modules}; do
  #     if lsmod | grep -q "^${dep}\b"; then
  #       modprobe -r "${dep}"
  #     fi
  #   done
  # fi
  lsmod | grep -q "^${module_name}\b" && rmmod "${module_name}"
}

start_process() {
  if status; then
    return 0
  fi

  log_msg "Starting process ..."
	check_with_build || return 1
  [ -L "/usr/lib/udev/rules.d/50-usb-aic-net.rules" ] && rm -f "/usr/lib/udev/rules.d/50-usb-aic-net.rules"
  [ ! -L "/usr/lib/udev/rules.d/50-usb-aic-net.rules" ] && ln -s "${TRIM_APPDEST}/server/udev/50-usb-aic-net.rules" "/usr/lib/udev/rules.d/50-usb-aic-net.rules"
  udevadm control --reload-rules
  udevadm trigger

  [ -L "/lib/firmware/aic8800D80" ] && rm -f "/lib/firmware/aic8800D80"
  [ ! -L "/lib/firmware/aic8800D80" ] && ln -s "${TRIM_APPDEST}/server/fw/aic8800D80" "/lib/firmware/aic8800D80"

  insmod_from_file "${TRIM_APPDEST}/server/src/aic_load_fw/aic_load_fw.ko" >>${LOG_FILE} 2>&1
  insmod_from_file "${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" >>${LOG_FILE} 2>&1
  return 0
}

stop_process() {
  log_msg "Stopping process ..."
  rmmod_from_file "${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" >>${LOG_FILE} 2>&1
  rmmod_from_file "${TRIM_APPDEST}/server/src/aic_load_fw/aic_load_fw.ko" >>${LOG_FILE} 2>&1

  [ -L "/lib/firmware/aic8800D80" ] && rm -f "/lib/firmware/aic8800D80"

  [ -L "/usr/lib/udev/rules.d/50-usb-aic-net.rules" ] && rm -f "/usr/lib/udev/rules.d/50-usb-aic-net.rules"
  udevadm control --reload-rules
  udevadm trigger
  return 0
}

status() {
  lsmod | grep -q '^aic8800_fdrv\b' 2>/dev/null && lsmod | grep -q '^aic_load_fw\b' 2>/dev/null
  return $?
}

case $1 in
  start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
  stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
  status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then
      exit 0
    else
      exit 3
    fi
    ;;
  *)
    exit 1
    ;;
esac
