#!/bin/bash

### This script is called after the user uninstalls the application.

for F in "/usr/lib/firmware/regulatory.db" "/usr/lib/firmware/regulatory.db.p7s"; do
  if [ "$(readlink -f "${F}")" = "${F}-upstream" ] && [ -f "${F}-debian" ]; then
    rm -f "${F}"
    ln -vsf "${F}-debian" "${F}" || true
  fi
done

apt purge -y iw
apt autoremove -y

exit $?
