#!/bin/bash

### This script is called after the user installs the application.

KVER="$(uname -r)"
#SVER="$(echo "${KVER}" | cut -d'.' -f1,2)"

# Prepare build environment
if [ ! -f "${TRIM_APPDEST}/server/src/Makefile" ]; then
  echo "Source code for wl not found." >$TRIM_TEMP_LOGFILE
  exit 1
fi

# Build the module
bash "$(dirname "$0")/chroot_make.sh" --pkgs build-essential bc -- \
  make -C /lib/modules/${KVER}/build M="${TRIM_APPDEST}/server/src" modules 2>$TRIM_TEMP_LOGFILE
[ $? -ne 0 ] && exit 1

if [ ! -f "${TRIM_APPDEST}/server/src/wl.ko" ]; then
  echo "Build wl module failed." >$TRIM_TEMP_LOGFILE
  exit 1
fi

# # Install the module
# mkdir -p /usr/lib/modules/${KVER}/updates/drivers/net/wireless
# rm -f /usr/lib/modules/${KVER}/updates/drivers/net/wireless/wl.ko 2>/dev/null || true
# cp -vpf "${TRIM_APPDEST}/server/src/wl.ko" /usr/lib/modules/${KVER}/updates/drivers/net/wireless/wl.ko
# if [ $? -ne 0 ]; then
#   echo "Install wl module failed." >$TRIM_TEMP_LOGFILE
#   exit 1
# fi
# 
# depmod -a || true
# echo wl >/etc/modules-load.d/wl.conf
# if [ $? -ne 0 ]; then
#   echo "Update modules load failed." >$TRIM_TEMP_LOGFILE
#   exit 1
# fi
# 
# # Restart systemd-modules-load.service to load the module
# systemctl restart systemd-modules-load.service
# if [ $? -ne 0 ]; then
#   echo "Restart systemd-modules-load.service failed." >$TRIM_TEMP_LOGFILE
#   exit 1
# fi

exit 0
