#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

# write the command to start your program here
CMD=""

log_msg() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>${LOG_FILE}
}

start_process() {
  if status; then
    return 0
  fi

  log_msg "Starting process ..."
  TRIM_OVERLAYFS="${TRIM_PKGVAR}/trim_overlayfs" "${TRIM_APPDEST}/server/vmctl.sh" --start --single-port ${wizard_single_port:-6080} --mirror-port ${wizard_mirror_port:-6081} --novnc-passwd ${wizard_novnc_password:-passwd} >>${LOG_FILE} 2>$TRIM_TEMP_LOGFILE
  [ $? -ne 0 ] && {
    log_msg "Failed to start process: $(cat $TRIM_TEMP_LOGFILE)"
    return 1
  }

  return 0
}

stop_process() {
  log_msg "Stopping process ..."

  TRIM_OVERLAYFS="${TRIM_PKGVAR}/trim_overlayfs" "${TRIM_APPDEST}/server/vmctl.sh" --stop >>${LOG_FILE} 2>$TRIM_TEMP_LOGFILE
  return 0
}

status() {
  TRIM_OVERLAYFS="${TRIM_PKGVAR}/trim_overlayfs" "${TRIM_APPDEST}/server/vmctl.sh" --status
  return $?
}

case $1 in
  start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
  stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
  status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then
      exit 0
    else
      exit 3
    fi
    ;;
  *)
    exit 1
    ;;
esac
