#!/bin/bash

### This script is called after the user uninstalls the application.

# [ "${wizard_data_action:-}" == "delete" ] && TRIM_OVERLAYFS="${TRIM_PKGVAR}/trim_overlayfs" "${TRIM_APPDEST}/server/vmctl.sh" --uninstall
[ "${wizard_data_action:-}" == "delete" ] && rm -rf "${TRIM_PKGVAR}"

exit 0
